image: docker:19.03.13-dind

services:
  - docker:19.03.13-dind

default:
  before_script:
    - export VERSION="$(date +%Y%m%dT%H%M%S)_${CI_COMMIT_SHA:0:8}"

job-build:
  stage: build
  script:
    - docker build -t app .
    - mkdir image
    - docker save app | gzip - > image/app.tar.gz
  artifacts:
    paths:
      - image

job-test:
  stage: test
  script:
    - zcat image/app.tar.gz | docker load
    - docker run app pylint app.py

job-deploy:
  stage: deploy
  script:
    - zcat image/app.tar.gz | docker load
    - docker tag app "$DOCKER_HUB_LOGIN"/pmn_cicd:"$VERSION"
    - docker tag app "$DOCKER_HUB_LOGIN"/pmn_cicd:latest
    - docker login "$DOCKER_REGISTRY" --username "$DOCKER_HUB_LOGIN" --password "$DOCKER_HUB_PASSWORD"
    - docker push "$DOCKER_HUB_LOGIN"/pmn_cicd:"$VERSION"
    - docker push "$DOCKER_HUB_LOGIN"/pmn_cicd:latest