job-build:
  stage: build
  image: docker
  script:
    - docker login --username $DOCKER_HUB_LOGIN --password $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_LOGIN/pmn_cicd
    - docker push $DOCKER_HUB_LOGIN/pmn_cicd

job-test:
  stage: test
  image: $DOCKER_HUB_LOGIN/pmn_cicd
  script:
    - pylint app.py